### ISSUE TITLE
`packages.dhall` missing

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-codegen/purescript-ps-cst#5]
This misses a `packages.dhall` especially one that contains `boxes`

**Comment by flip111** [comment]
PR is welcome, otherwise one of us will pick it up in due time.

**Comment by i-am-the-slime** [comment]
I got it to run but all tests fail, is that expected?

**Comment by flip111** [comment]
@srghma could you please comment on the situation with the tests?

**Comment by srghma** [comment]
https://pursuit.purescript.org/packages/purescript-boxes/2.0.1/docs/Text.PrettyPrint.Boxes are here, but https://github.com/cdepillabout/purescript-boxes/pull/4, that's why tests didn't pass

Probably it wasn't committed because if my global gitignore

Apart from my pr to boxes the file is default one IIRC

Can add in 2 days, I'm in vacation now

**Comment by srghma** [comment]
done
